//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiToanGioTanHoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiGianDiChuyen
    {
        public string ToaNha { get; set; }
        public Nullable<double> Time_Stair_1Floor { get; set; }
        public Nullable<double> Time_Elavator_1Floor { get; set; }
        public Nullable<double> Time_Stair_To_Parking { get; set; }
        public Nullable<double> Time_Parking_To_Gate { get; set; }
    }
}
